$monitor1 = DP-1
$monitor2 = HDMI-A-1

workspace = ID:1, m[$monitor1]
workspace = ID:2, m[$monitor2]
workspace = ID:3, m[$monitor1]
workspace = ID:4, m[$monitor2]
workspace = 5, monitor:$monitor1
workspace = 6, monitor:$monitor2
workspace = 7, monitor:$monitor1
workspace = 8, monitor:$monitor2
