$monitor= eDP-1
workspace = 1, monitor:$monitor,persistent:true
workspace = 2, monitor:$monitor,persistent:true
workspace = 3, monitor:$monitor,persistent:true
workspace = 4, monitor:$monitor,persistent:true
workspace = 5, monitor:$monitor,persistent:true
workspace = 6, monitor:$monitor,persistent:true
workspace = 7, monitor:$monitor,persistent:true
workspace = 8, monitor:$monitor,persistent:true
