$foreground = rgb({foreground.strip})
$backgroundCol = rgb({color0.strip})
$color0 = rgba({color0.strip}FF)
$color1 = rgba({color1.strip}FF)
$color2 = rgba({color2.strip}FF)
$color3 = rgba({color3.strip}FF)
$color4 = rgba({color4.strip}FF)
$color5 = rgba({color5.strip}FF)
$color6 = rgba({color6.strip}FF)
$color7 = rgba({color7.strip}FF)
$color8 = rgba({color8.strip}FF)
$color9 = rgba({color9.strip}FF)
$color10 = rgba({color10.strip}FF)
$color11 = rgba({color11.strip}FF)
$color12 = rgba({color12.strip}FF)
$color13 = rgba({color13.strip}FF)
$color14 = rgba({color14.strip}FF)
$color15 = rgba({color15.strip}FF)
